name: Build libmodbus

on:
    push:
        branches: [ $default-branch ]
    pull_request:
        branches: [ $default-branch ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: configure
              run: ./autogen.sh && ./configure
            - name: make
              run: make
            - name: make distcheck
              run: make distcheck

    build_cmake:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Configure CMake
              run:  cmake -B ${{github.workspace}}/build
            - name: Build
              run: cmake --build ${{github.workspace}}/build
